// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  name: 'Test Environment',
  production: false,
  version: env.npm_package_version,
  serverUrl: 'http://test.serpek.com/',
  defaultLanguage: 'tr-TR',
  supportedLanguages: ['en-US', 'tr-TR']
};
