// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  name: 'Production Environment',
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://api.serpek.com/',
  defaultLanguage: 'tr-TR',
  supportedLanguages: ['en-US', 'tr-TR']
};
